config/routes.rb
Rails.application.routes.draw do
  get 'flickr/index'
  get 'flickr/search'
  root 'flickr#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/flickr_controller.rb
class FlickrController < ApplicationController
  def index
  end

  def search
    if params[:q].to_s.strip.length > 0
      @page = params[:page].to_i > 0 ? params[:page].to_i : 1
      @photos_list = flickr.photos.search(text: params[:q], page: @page, per_page: 20)
      render 'search'
    else
      render nothing: true
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flickr_helper.rb
module FlickrHelper
end

app/views/flickr/index.html.haml
.header
  %h1
    Flickr Search
  = form_tag flickr_search_path,remote: true, method: :get, class: 'search' do
    = text_field_tag(:q)
    = submit_tag('Search')
.fk-thumbnails
.lb-container
  %h2
    %span.lb-close
      x
    %span.lb-title
  %img.lb-image
  .lb-arrow.lb-prev
    &lt;
  .lb-arrow.lb-next
    &gt;
.pg-container
  .pg-pager.pg-hidden
    =link_to 'More', flickr_search_path, remote: true, class: 'more-photo'

app/views/flickr/search.js.erb
<% if @page == 1 %>
  $('.fk-thumbnails').empty();
  $('.pg-pager').addClass('pg-hidden');
<% end %>
<% @photos_list.each do |photo| %>
  var thumb = document.createElement("img");
  thumb.className = 'fk-photo';
  thumb.src = '<%= FlickRaw.url_q(photo) %>'
  thumb.setAttribute('data-large', '<%= FlickRaw.url(photo) %>');
  thumb.setAttribute('data-title', '<%= photo.title %>');
  $('.fk-thumbnails').append(thumb);
<% end %>
<% if @page < @photos_list.pages %>
  $('.pg-pager').removeClass('pg-hidden');
  $('a.more-photo').attr('href', '<%= flickr_search_path(q: params[:q], page: @page + 1).html_safe %>');
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FlickrSearch</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>